// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: faas/functions/v1/function_service.proto

package functions

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ImportFunctionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ImportFunctionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImportFunctionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ImportFunctionsRequestMultiError, or nil if none found.
func (m *ImportFunctionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ImportFunctionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArchiveSources() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ImportFunctionsRequestValidationError{
						field:  fmt.Sprintf("ArchiveSources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ImportFunctionsRequestValidationError{
						field:  fmt.Sprintf("ArchiveSources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ImportFunctionsRequestValidationError{
					field:  fmt.Sprintf("ArchiveSources[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ImportFunctionsRequestMultiError(errors)
	}

	return nil
}

// ImportFunctionsRequestMultiError is an error wrapping multiple validation
// errors returned by ImportFunctionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ImportFunctionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImportFunctionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImportFunctionsRequestMultiError) AllErrors() []error { return m }

// ImportFunctionsRequestValidationError is the validation error returned by
// ImportFunctionsRequest.Validate if the designated constraints aren't met.
type ImportFunctionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImportFunctionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImportFunctionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImportFunctionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImportFunctionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImportFunctionsRequestValidationError) ErrorName() string {
	return "ImportFunctionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ImportFunctionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImportFunctionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImportFunctionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImportFunctionsRequestValidationError{}

// Validate checks the field values on ArchiveSource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArchiveSource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArchiveSource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArchiveSourceMultiError, or
// nil if none found.
func (m *ArchiveSource) ValidateAll() error {
	return m.validate(true)
}

func (m *ArchiveSource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FunctionName

	// no validation rules for Content

	if len(errors) > 0 {
		return ArchiveSourceMultiError(errors)
	}

	return nil
}

// ArchiveSourceMultiError is an error wrapping multiple validation errors
// returned by ArchiveSource.ValidateAll() if the designated constraints
// aren't met.
type ArchiveSourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArchiveSourceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArchiveSourceMultiError) AllErrors() []error { return m }

// ArchiveSourceValidationError is the validation error returned by
// ArchiveSource.Validate if the designated constraints aren't met.
type ArchiveSourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArchiveSourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArchiveSourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArchiveSourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArchiveSourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArchiveSourceValidationError) ErrorName() string { return "ArchiveSourceValidationError" }

// Error satisfies the builtin error interface
func (e ArchiveSourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArchiveSource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArchiveSourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArchiveSourceValidationError{}

// Validate checks the field values on ImportFunctionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ImportFunctionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImportFunctionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ImportFunctionsResponseMultiError, or nil if none found.
func (m *ImportFunctionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ImportFunctionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFunctions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ImportFunctionsResponseValidationError{
						field:  fmt.Sprintf("Functions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ImportFunctionsResponseValidationError{
						field:  fmt.Sprintf("Functions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ImportFunctionsResponseValidationError{
					field:  fmt.Sprintf("Functions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ImportFunctionsResponseMultiError(errors)
	}

	return nil
}

// ImportFunctionsResponseMultiError is an error wrapping multiple validation
// errors returned by ImportFunctionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ImportFunctionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImportFunctionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImportFunctionsResponseMultiError) AllErrors() []error { return m }

// ImportFunctionsResponseValidationError is the validation error returned by
// ImportFunctionsResponse.Validate if the designated constraints aren't met.
type ImportFunctionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImportFunctionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImportFunctionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImportFunctionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImportFunctionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImportFunctionsResponseValidationError) ErrorName() string {
	return "ImportFunctionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ImportFunctionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImportFunctionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImportFunctionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImportFunctionsResponseValidationError{}

// Validate checks the field values on ImportFunctionsMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ImportFunctionsMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImportFunctionsMetadata with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ImportFunctionsMetadataMultiError, or nil if none found.
func (m *ImportFunctionsMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *ImportFunctionsMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCount

	{
		sorted_keys := make([]string, len(m.GetFailedImports()))
		i := 0
		for key := range m.GetFailedImports() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetFailedImports()[key]
			_ = val

			// no validation rules for FailedImports[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ImportFunctionsMetadataValidationError{
							field:  fmt.Sprintf("FailedImports[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ImportFunctionsMetadataValidationError{
							field:  fmt.Sprintf("FailedImports[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ImportFunctionsMetadataValidationError{
						field:  fmt.Sprintf("FailedImports[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return ImportFunctionsMetadataMultiError(errors)
	}

	return nil
}

// ImportFunctionsMetadataMultiError is an error wrapping multiple validation
// errors returned by ImportFunctionsMetadata.ValidateAll() if the designated
// constraints aren't met.
type ImportFunctionsMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImportFunctionsMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImportFunctionsMetadataMultiError) AllErrors() []error { return m }

// ImportFunctionsMetadataValidationError is the validation error returned by
// ImportFunctionsMetadata.Validate if the designated constraints aren't met.
type ImportFunctionsMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImportFunctionsMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImportFunctionsMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImportFunctionsMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImportFunctionsMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImportFunctionsMetadataValidationError) ErrorName() string {
	return "ImportFunctionsMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e ImportFunctionsMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImportFunctionsMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImportFunctionsMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImportFunctionsMetadataValidationError{}
