// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: faas/functions/v1/function_service.proto

package functionspb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionRequestMultiError, or nil if none found.
func (m *UploadFunctionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Data.(type) {
	case *UploadFunctionRequest_Function:
		if v == nil {
			err := UploadFunctionRequestValidationError{
				field:  "Data",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetFunction()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "Function",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UploadFunctionRequestValidationError{
						field:  "Function",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFunction()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UploadFunctionRequestValidationError{
					field:  "Function",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *UploadFunctionRequest_Chunk:
		if v == nil {
			err := UploadFunctionRequestValidationError{
				field:  "Data",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Chunk
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UploadFunctionRequestMultiError(errors)
	}

	return nil
}

// UploadFunctionRequestMultiError is an error wrapping multiple validation
// errors returned by UploadFunctionRequest.ValidateAll() if the designated
// constraints aren't met.
type UploadFunctionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionRequestMultiError) AllErrors() []error { return m }

// UploadFunctionRequestValidationError is the validation error returned by
// UploadFunctionRequest.Validate if the designated constraints aren't met.
type UploadFunctionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionRequestValidationError) ErrorName() string {
	return "UploadFunctionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionRequestValidationError{}

// Validate checks the field values on UploadFunctionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadFunctionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFunctionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFunctionResponseMultiError, or nil if none found.
func (m *UploadFunctionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFunctionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFunction()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UploadFunctionResponseValidationError{
					field:  "Function",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UploadFunctionResponseValidationError{
					field:  "Function",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFunction()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UploadFunctionResponseValidationError{
				field:  "Function",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UploadFunctionResponseMultiError(errors)
	}

	return nil
}

// UploadFunctionResponseMultiError is an error wrapping multiple validation
// errors returned by UploadFunctionResponse.ValidateAll() if the designated
// constraints aren't met.
type UploadFunctionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFunctionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFunctionResponseMultiError) AllErrors() []error { return m }

// UploadFunctionResponseValidationError is the validation error returned by
// UploadFunctionResponse.Validate if the designated constraints aren't met.
type UploadFunctionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFunctionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFunctionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFunctionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFunctionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFunctionResponseValidationError) ErrorName() string {
	return "UploadFunctionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFunctionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFunctionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFunctionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFunctionResponseValidationError{}
