// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faas/functions/v1/function_service.proto

package functionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFunctionRequest_Function
	//	*UploadFunctionRequest_Chunk
	Data          isUploadFunctionRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFunctionRequest) Reset() {
	*x = UploadFunctionRequest{}
	mi := &file_faas_functions_v1_function_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFunctionRequest) ProtoMessage() {}

func (x *UploadFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_functions_v1_function_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFunctionRequest.ProtoReflect.Descriptor instead.
func (*UploadFunctionRequest) Descriptor() ([]byte, []int) {
	return file_faas_functions_v1_function_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFunctionRequest) GetData() isUploadFunctionRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFunctionRequest) GetFunction() *Function {
	if x != nil {
		if x, ok := x.Data.(*UploadFunctionRequest_Function); ok {
			return x.Function
		}
	}
	return nil
}

func (x *UploadFunctionRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFunctionRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFunctionRequest_Data interface {
	isUploadFunctionRequest_Data()
}

type UploadFunctionRequest_Function struct {
	Function *Function `protobuf:"bytes,1,opt,name=function,proto3,oneof"`
}

type UploadFunctionRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFunctionRequest_Function) isUploadFunctionRequest_Data() {}

func (*UploadFunctionRequest_Chunk) isUploadFunctionRequest_Data() {}

type UploadFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *Function              `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFunctionResponse) Reset() {
	*x = UploadFunctionResponse{}
	mi := &file_faas_functions_v1_function_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFunctionResponse) ProtoMessage() {}

func (x *UploadFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_functions_v1_function_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFunctionResponse.ProtoReflect.Descriptor instead.
func (*UploadFunctionResponse) Descriptor() ([]byte, []int) {
	return file_faas_functions_v1_function_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFunctionResponse) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

var File_faas_functions_v1_function_service_proto protoreflect.FileDescriptor

const file_faas_functions_v1_function_service_proto_rawDesc = "" +
	"\n" +
	"(faas/functions/v1/function_service.proto\x12\x11faas.functions.v1\x1a faas/functions/v1/function.proto\"r\n" +
	"\x15UploadFunctionRequest\x129\n" +
	"\bfunction\x18\x01 \x01(\v2\x1b.faas.functions.v1.FunctionH\x00R\bfunction\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"Q\n" +
	"\x16UploadFunctionResponse\x127\n" +
	"\bfunction\x18\x01 \x01(\v2\x1b.faas.functions.v1.FunctionR\bfunction2z\n" +
	"\x0fFunctionService\x12g\n" +
	"\x0eUploadFunction\x12(.faas.functions.v1.UploadFunctionRequest\x1a).faas.functions.v1.UploadFunctionResponse(\x01B@Z>github.com/10Narratives/faas/pkg/faas/functions/v1;functionspbb\x06proto3"

var (
	file_faas_functions_v1_function_service_proto_rawDescOnce sync.Once
	file_faas_functions_v1_function_service_proto_rawDescData []byte
)

func file_faas_functions_v1_function_service_proto_rawDescGZIP() []byte {
	file_faas_functions_v1_function_service_proto_rawDescOnce.Do(func() {
		file_faas_functions_v1_function_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_functions_v1_function_service_proto_rawDesc), len(file_faas_functions_v1_function_service_proto_rawDesc)))
	})
	return file_faas_functions_v1_function_service_proto_rawDescData
}

var file_faas_functions_v1_function_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faas_functions_v1_function_service_proto_goTypes = []any{
	(*UploadFunctionRequest)(nil),  // 0: faas.functions.v1.UploadFunctionRequest
	(*UploadFunctionResponse)(nil), // 1: faas.functions.v1.UploadFunctionResponse
	(*Function)(nil),               // 2: faas.functions.v1.Function
}
var file_faas_functions_v1_function_service_proto_depIdxs = []int32{
	2, // 0: faas.functions.v1.UploadFunctionRequest.function:type_name -> faas.functions.v1.Function
	2, // 1: faas.functions.v1.UploadFunctionResponse.function:type_name -> faas.functions.v1.Function
	0, // 2: faas.functions.v1.FunctionService.UploadFunction:input_type -> faas.functions.v1.UploadFunctionRequest
	1, // 3: faas.functions.v1.FunctionService.UploadFunction:output_type -> faas.functions.v1.UploadFunctionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_faas_functions_v1_function_service_proto_init() }
func file_faas_functions_v1_function_service_proto_init() {
	if File_faas_functions_v1_function_service_proto != nil {
		return
	}
	file_faas_functions_v1_function_proto_init()
	file_faas_functions_v1_function_service_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadFunctionRequest_Function)(nil),
		(*UploadFunctionRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_functions_v1_function_service_proto_rawDesc), len(file_faas_functions_v1_function_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_functions_v1_function_service_proto_goTypes,
		DependencyIndexes: file_faas_functions_v1_function_service_proto_depIdxs,
		MessageInfos:      file_faas_functions_v1_function_service_proto_msgTypes,
	}.Build()
	File_faas_functions_v1_function_service_proto = out.File
	file_faas_functions_v1_function_service_proto_goTypes = nil
	file_faas_functions_v1_function_service_proto_depIdxs = nil
}
