// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faas/functions/v1/function.proto

package functionspb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A serverless function resource.
type Function struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the function.
	// Format: `functions/{function_id}`
	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParametersSchema string `protobuf:"bytes,2,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"`
	// The entry point file for the function.
	Entrypoint string `protobuf:"bytes,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// The path to the source code in the storage system.
	SourcePath    string `protobuf:"bytes,4,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_faas_functions_v1_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_faas_functions_v1_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_faas_functions_v1_function_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetParametersSchema() string {
	if x != nil {
		return x.ParametersSchema
	}
	return ""
}

func (x *Function) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *Function) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

var File_faas_functions_v1_function_proto protoreflect.FileDescriptor

const file_faas_functions_v1_function_proto_rawDesc = "" +
	"\n" +
	" faas/functions/v1/function.proto\x12\x11faas.functions.v1\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\"\x81\x02\n" +
	"\bFunction\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x127\n" +
	"\x11parameters_schema\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x10parametersSchema\x12*\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\n" +
	"entrypoint\x12+\n" +
	"\vsource_path\x18\x04 \x01(\tB\n" +
	"\xe0A\x03\xfaB\x04r\x02\x10\x01R\n" +
	"sourcePath:J\xeaAG\n" +
	"\x1afaas.functions.v1/Function\x12\x14functions/{function}*\tfunctions2\bfunctionB@Z>github.com/10Narratives/faas/pkg/faas/functions/v1;functionspbb\x06proto3"

var (
	file_faas_functions_v1_function_proto_rawDescOnce sync.Once
	file_faas_functions_v1_function_proto_rawDescData []byte
)

func file_faas_functions_v1_function_proto_rawDescGZIP() []byte {
	file_faas_functions_v1_function_proto_rawDescOnce.Do(func() {
		file_faas_functions_v1_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faas_functions_v1_function_proto_rawDesc), len(file_faas_functions_v1_function_proto_rawDesc)))
	})
	return file_faas_functions_v1_function_proto_rawDescData
}

var file_faas_functions_v1_function_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_faas_functions_v1_function_proto_goTypes = []any{
	(*Function)(nil), // 0: faas.functions.v1.Function
}
var file_faas_functions_v1_function_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faas_functions_v1_function_proto_init() }
func file_faas_functions_v1_function_proto_init() {
	if File_faas_functions_v1_function_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faas_functions_v1_function_proto_rawDesc), len(file_faas_functions_v1_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_faas_functions_v1_function_proto_goTypes,
		DependencyIndexes: file_faas_functions_v1_function_proto_depIdxs,
		MessageInfos:      file_faas_functions_v1_function_proto_msgTypes,
	}.Build()
	File_faas_functions_v1_function_proto = out.File
	file_faas_functions_v1_function_proto_goTypes = nil
	file_faas_functions_v1_function_proto_depIdxs = nil
}
